[package]
name = "symlist"


version = "0.1.0"


edition = "2024"

[dependencies]
clap = { version = "4.6.1", features = ["derive"] }
clap_complete = { version = "4.6.5", features = ["unstable-dynamic"] }
color-eyre = "0.6.5"
tempfile = "3.27.0"


[lints.clippy]
uninlined_format_args = "warn"
new_without_default = "allow"
